Repository Lucia560/Jakarta_labb, pull requests merged in 2024-03, with the labels that each got.

#48 Added function delete branch in pipeline
  .github/workflows/maven.yml
Labels: devops

#45 37 implement validation
  pom.xml
  src/main/java/org/example/jakarta_labb/dto/MovieDto.java
  src/main/java/org/example/jakarta_labb/validate/CustomReleaseYear.java
  src/main/java/org/example/jakarta_labb/validate/CustomReleaseYearValidator.java
  src/main/java/org/example/jakarta_labb/validate/ReleaseYear.java
  src/test/java/org/example/jakarta_labb/dto/MovieDtoTest.java
  src/test/java/org/example/jakarta_labb/dto/MoviesTest.java
  src/test/java/org/example/jakarta_labb/entity/MovieTest.java
  src/test/java/org/example/jakarta_labb/exceptionmapper/.gitkeep
  src/test/java/org/example/jakarta_labb/repository/.gitkeep
  src/test/java/org/example/jakarta_labb/resource/.gitkeep
  src/test/java/org/example/jakarta_labb/validate/CustomReleaseYearValidatorTest.java
  src/test/java/org/example/jakarta_labb/validate/ReleaseYearTest.java
Labels: enhancement, major

#51 Add dependabot file to github
  .github/dependabot.yml
Labels: devops

#52 Update README.md
  README.md
Labels: documentation, minor

#56 Movie exception mapper
  pom.xml
  src/main/java/org/example/jakarta_labb/exceptionmapper/.gitkeep
  src/main/java/org/example/jakarta_labb/exceptionmapper/MovieException.java
  src/main/java/org/example/jakarta_labb/exceptionmapper/MovieExceptionMapper.java
  src/main/java/org/example/jakarta_labb/exceptionmapper/MovieNotFoundException.java
  src/main/java/org/example/jakarta_labb/exceptionmapper/MovieValidationException.java
  src/test/java/org/example/jakarta_labb/exceptionmapper/MovieExceptionMapperTest.java
Labels: enhancement

#57 Issue47
  src/main/java/org/example/jakarta_labb/dto/MovieDto.java
  src/main/java/org/example/jakarta_labb/dto/Movies.java
  src/main/java/org/example/jakarta_labb/repository/MovieRepository.java
  src/main/java/org/example/jakarta_labb/resource/MovieResource.java
Labels: enhancement

#61 49 test for movieresource class
  pom.xml
  src/main/java/org/example/jakarta_labb/resource/MovieResource.java
  src/test/java/org/example/jakarta_labb/resource/.gitkeep
  src/test/java/org/example/jakarta_labb/resource/MovieResourceTest.java
Labels: enhancement

#64 Update configuration
  wildfly-docker-config.sh
Labels: bug
