Repository Lucia560/Jakarta_labb, pull requests merged in 2024-02, with the labels that each got.

#9 Added MIT-License
  LICENSE
Labels: documentation

#11 remove-.idea-folder
  .idea/.gitignore
  .idea/encodings.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: bug

#10 Created .editorconfig
  .editorconfig
Labels: devops

#16 add movie entity
  src/main/java/org/example/jakarta_labb/Movie.java
  src/test/java/org/example/jakarta_labb/MovieTest.java
Labels: enhancement

#19 18 fix project structure
  pom.xml
  src/main/java/org/example/jakarta_labb/dto/PersonDtoTemplate.java
  src/main/java/org/example/jakarta_labb/dto/PersonsTemplate.java
  src/main/java/org/example/jakarta_labb/entity/PersonTemplate.java
  src/main/java/org/example/jakarta_labb/repository/PersonRepositoryTemplate.java
  src/main/java/org/example/jakarta_labb/resource/HelloResource.java
  src/main/java/org/example/jakarta_labb/resource/PersonResourceTemplate.java
  src/main/resources/META-INF/persistence.xml
  src/main/resources/WEB-INF/jboss-web.xml
  src/main/webapp/index.html
  src/test/java/org/example/jakarta_labb/HelloResourceTest.java
Labels: enhancement, major

#22 Add .dockerignore
  .dockerignore
Labels: devops

#27 Add sonarcloud and jacoco
  .github/workflows/sonarcloud.yml
  pom.xml
Labels: devops

#26 Crud operations
  src/main/java/org/example/jakarta_labb/entity/Movie.java
  src/main/java/org/example/jakarta_labb/repository/MovieRepository.java
  src/main/java/org/example/jakarta_labb/resource/MovieResource.java
  src/test/java/org/example/jakarta_labb/entity/MovieTest.java
  src/test/java/org/example/jakarta_labb/resource/HelloResourceTest.java
Labels: enhancement

#38 36 add gitkeep in empty directories
  src/main/java/org/example/jakarta_labb/HelloApplication.java
  src/main/java/org/example/jakarta_labb/dto/.gitkeep
  src/main/java/org/example/jakarta_labb/dto/PersonDtoTemplate.java
  src/main/java/org/example/jakarta_labb/dto/PersonsTemplate.java
  src/main/java/org/example/jakarta_labb/entity/PersonTemplate.java
  src/main/java/org/example/jakarta_labb/exceptionmapper/.gitkeep
  src/main/java/org/example/jakarta_labb/repository/PersonRepositoryTemplate.java
  src/main/java/org/example/jakarta_labb/resource/PersonResourceTemplate.java
  src/main/java/org/example/jakarta_labb/validate/.gitkeep
Labels: enhancement

#34 Replace CD with WORKDIR
  Dockerfile
Labels: devops, minor

#39 28 implement moviedto and movies class
  src/main/java/org/example/jakarta_labb/dto/.gitkeep
  src/main/java/org/example/jakarta_labb/dto/MovieDto.java
  src/main/java/org/example/jakarta_labb/dto/Movies.java
  src/test/java/org/example/jakarta_labb/MovieDtoTest.java
  src/test/java/org/example/jakarta_labb/MovieTest.java
  src/test/java/org/example/jakarta_labb/MoviesTest.java
  src/test/java/org/example/jakarta_labb/resource/HelloResourceTest.java
Labels: enhancement

#41 Solved a few issues to get the application running.
  .dockerignore
  commands.cli
  docker-compose.yml
  src/main/java/org/example/jakarta_labb/resource/MovieResource.java
  src/main/resources/META-INF/persistence.xml
Labels: major

#43 Add maven surefire pluggin to pom file
  pom.xml
Labels: bug, devops
